name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/${{ env.VERSION }}/${{ env.TARGET }}.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
       env:
         VERSION: "v0.4.36"
         TARGET: "mdbook-v0.4.36-x86_64-unknown-linux-gnu"

      - name: Download mdbook-catppuccin
        run: |
          curl -sSL https://github.com/catppuccin/mdBook/releases/download/${{ env.VERSION }}/${{ env.TARGET }}.tar.gz | tar -xz
          echo `pwd`/${{ env.TARGET }} >> $GITHUB_PATH
        env:
          VERSION: "v2.1.0"
          TARGET: "mdbook-catppuccin-x86_64-unknown-linux-gnu"

      - name: Download mdbook-admonish
        run: |
          mkdir ${{ env.TARGET }}
          curl -sSL https://github.com/tommilligan/mdbook-admonish/releases/download/${{ env.VERSION }}/${{ env.TARGET }}.tar.gz | tar -xz --directory=${{ env.TARGET }}          echo `pwd`/${{ env.TARGET }} >> $GITHUB_PATH
        env:
          VERSION: "v1.14.0"
          TARGET: "mdbook-admonish-v1.13.0-x86_64-unknown-linux-gnu"

      - name: Build mdBook
        run: |
          mdbook-admonish install
          mdbook-catppuccin install
          mdbook build

      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
